library(dplyr)
library(readxl)
library(lubridate)
library(arrow)

# Load the data and match columns
df_2010_2017 <- read_xlsx("data/01_raw/reporte-adjudicaciones/3. Reporte Contratos 201-2017.xlsx") 

df_2010_2017 <- df_2010_2017 %>%
    transmute(
        CODIGO_CONTRATO = CODIGO_CONTRATO,
        NUM_CONTRATO = `Nº CONTRATO`,
        FECHA_VIGENCIA_INICIAL = `FECHA VIGENCIA INICIAL`,
        FECHA_VIGENCIA_FINAL = `FECHA VIGENCIA FINAL`,
        FECHA_SUSCRIPCION_CONTRATO = `FECHA SUSCRIPCION CONTRATO`,
        FECHA_PUBLICACION_CONTRATO = `FECHA_PUBLICACION_CONTRATO`,
        RUC_DESTINATARIO_PAGO = `RUC DESTINO PAGO`,
        MONEDA = MONEDA,
        MONTO_CONTRATADO_TOTAL = MON_CONT_TOTAL,
        MONTO_CONTRATADO_ITEM = `VALOR REFERENCIAL ITEM`,
        DESCRIPCION_PROCESO = `DESCRIPCION PROCESO`,
        CODIGOCONVOCATORIA = PROCESO,
        MODALIDAD = MODALIDAD,
        TIPO_PROCESO = `TIPO PROCESO`
    ) %>% 
    mutate(
        CODIGO_CONTRATO = as.character(CODIGO_CONTRATO),
        NUM_CONTRATO = as.character(NUM_CONTRATO),
        FECHA_VIGENCIA_INICIAL = as.POSIXct(FECHA_VIGENCIA_INICIAL),
        FECHA_VIGENCIA_FINAL = as.POSIXct(FECHA_VIGENCIA_FINAL),
        FECHA_SUSCRIPCION_CONTRATO = as.POSIXct(FECHA_SUSCRIPCION_CONTRATO),
        FECHA_PUBLICACION_CONTRATO = as.POSIXct(FECHA_PUBLICACION_CONTRATO),
        RUC_DESTINATARIO_PAGO = as.character(RUC_DESTINATARIO_PAGO),
        MONEDA = as.character(MONEDA),
        MONTO_CONTRATADO_TOTAL = as.numeric(MONTO_CONTRATADO_TOTAL),
        MONTO_CONTRATADO_ITEM = as.numeric(MONTO_CONTRATADO_ITEM),
        DESCRIPCION_PROCESO = as.character(DESCRIPCION_PROCESO),
        CODIGOCONVOCATORIA = as.character(CODIGOCONVOCATORIA),
        MODALIDAD = as.character(MODALIDAD),
        TIPO_PROCESO = as.character(TIPO_PROCESO)
    )

df_2018 <- read_xlsx("data/01_raw/CONOSCE/CONOSCE_CONTRATOS2018_0.xlsx") 
df_2018 <- df_2018 %>%
    transmute(
        CODIGO_CONTRATO = CODIGO_CONTRATO,
        NUM_CONTRATO = NUM_CONTRATO,
        FECHA_VIGENCIA_INICIAL = FECHA_VIGENCIA_INICIAL,
        FECHA_VIGENCIA_FINAL = FECHA_VIGENCIA_FINAL,
        FECHA_SUSCRIPCION_CONTRATO = FECHA_SUSCRIPCION_CONTRATO,
        FECHA_PUBLICACION_CONTRATO = FECHA_PUBLICACION_CONTRATO,
        RUC_DESTINATARIO_PAGO = RUC_DESTINATARIO_PAGO,
        MONEDA = MONEDA,
        MONTO_CONTRATADO_TOTAL = MONTO_CONTRATADO_TOTAL,
        MONTO_CONTRATADO_ITEM = MONTO_CONTRATADO_ITEM,
        DESCRIPCION_PROCESO = DESCRIPCION_PROCESO,
        CODIGOCONVOCATORIA = CODIGOCONVOCATORIA,
        MODALIDAD = NA,
        TIPO_PROCESO = NA
    ) %>%
    mutate(
        CODIGO_CONTRATO = as.character(CODIGO_CONTRATO),
        NUM_CONTRATO = as.character(NUM_CONTRATO),
        FECHA_VIGENCIA_INICIAL = as.POSIXct(FECHA_VIGENCIA_INICIAL),
        FECHA_VIGENCIA_FINAL = as.POSIXct(FECHA_VIGENCIA_FINAL),
        FECHA_SUSCRIPCION_CONTRATO = as.POSIXct(FECHA_SUSCRIPCION_CONTRATO),
        FECHA_PUBLICACION_CONTRATO = as.POSIXct(FECHA_PUBLICACION_CONTRATO),
        RUC_DESTINATARIO_PAGO = as.character(RUC_DESTINATARIO_PAGO),
        MONEDA = as.character(MONEDA),
        MONTO_CONTRATADO_TOTAL = as.numeric(MONTO_CONTRATADO_TOTAL),
        MONTO_CONTRATADO_ITEM = as.numeric(MONTO_CONTRATADO_ITEM),
        DESCRIPCION_PROCESO = as.character(DESCRIPCION_PROCESO),
        CODIGOCONVOCATORIA = as.character(CODIGOCONVOCATORIA)
    )

df_2019 <- read_xlsx("data/01_raw/CONOSCE/CONOSCE_CONTRATOS2019_0.xlsx") 
df_2019 <- df_2019 %>%
    transmute(
        CODIGO_CONTRATO = CODIGO_CONTRATO,
        NUM_CONTRATO = NUM_CONTRATO,
        FECHA_VIGENCIA_INICIAL = FECHA_VIGENCIA_INICIAL,
        FECHA_VIGENCIA_FINAL = FECHA_VIGENCIA_FINAL,
        FECHA_SUSCRIPCION_CONTRATO = FECHA_SUSCRIPCION_CONTRATO,
        FECHA_PUBLICACION_CONTRATO = FECHA_PUBLICACION_CONTRATO,
        RUC_DESTINATARIO_PAGO = RUC_DESTINATARIO_PAGO,
        MONEDA = MONEDA,
        MONTO_CONTRATADO_TOTAL = MONTO_CONTRATADO_TOTAL,
        MONTO_CONTRATADO_ITEM = MONTO_CONTRATADO_ITEM,
        DESCRIPCION_PROCESO = DESCRIPCION_PROCESO,
        CODIGOCONVOCATORIA = CODIGOCONVOCATORIA,
        MODALIDAD = NA,
        TIPO_PROCESO = NA
    ) %>%
    mutate(
        CODIGO_CONTRATO = as.character(CODIGO_CONTRATO),
        NUM_CONTRATO = as.character(NUM_CONTRATO),
        FECHA_VIGENCIA_INICIAL = as.POSIXct(FECHA_VIGENCIA_INICIAL),
        FECHA_VIGENCIA_FINAL = as.POSIXct(FECHA_VIGENCIA_FINAL),
        FECHA_SUSCRIPCION_CONTRATO = as.POSIXct(FECHA_SUSCRIPCION_CONTRATO),
        FECHA_PUBLICACION_CONTRATO = as.POSIXct(FECHA_PUBLICACION_CONTRATO),
        RUC_DESTINATARIO_PAGO = as.character(RUC_DESTINATARIO_PAGO),
        MONEDA = as.character(MONEDA),
        MONTO_CONTRATADO_TOTAL = as.numeric(MONTO_CONTRATADO_TOTAL),
        MONTO_CONTRATADO_ITEM = as.numeric(MONTO_CONTRATADO_ITEM),
        DESCRIPCION_PROCESO = as.character(DESCRIPCION_PROCESO),
        CODIGOCONVOCATORIA = as.character(CODIGOCONVOCATORIA)
    )

df_2020 <- read_xlsx("data/01_raw/CONOSCE/CONOSCE_CONTRATOS2020_0.xlsx") 
df_2020 <- df_2020 %>%
    transmute(
        CODIGO_CONTRATO = CODIGO_CONTRATO,
        NUM_CONTRATO = NUM_CONTRATO,
        FECHA_VIGENCIA_INICIAL = FECHA_VIGENCIA_INICIAL,
        FECHA_VIGENCIA_FINAL = FECHA_VIGENCIA_FINAL,
        FECHA_SUSCRIPCION_CONTRATO = FECHA_SUSCRIPCION_CONTRATO,
        FECHA_PUBLICACION_CONTRATO = FECHA_PUBLICACION_CONTRATO,
        RUC_DESTINATARIO_PAGO = RUC_DESTINATARIO_PAGO,
        MONEDA = MONEDA,
        MONTO_CONTRATADO_TOTAL = MONTO_CONTRATADO_TOTAL,
        MONTO_CONTRATADO_ITEM = MONTO_CONTRATADO_ITEM,
        DESCRIPCION_PROCESO = DESCRIPCION_PROCESO,
        CODIGOCONVOCATORIA = CODIGOCONVOCATORIA,
        MODALIDAD = NA,
        TIPO_PROCESO = NA
    ) %>%
    mutate(
        CODIGO_CONTRATO = as.character(CODIGO_CONTRATO),
        NUM_CONTRATO = as.character(NUM_CONTRATO),
        FECHA_VIGENCIA_INICIAL = as.POSIXct(FECHA_VIGENCIA_INICIAL),
        FECHA_VIGENCIA_FINAL = as.POSIXct(FECHA_VIGENCIA_FINAL),
        FECHA_SUSCRIPCION_CONTRATO = as.POSIXct(FECHA_SUSCRIPCION_CONTRATO),
        FECHA_PUBLICACION_CONTRATO = as.POSIXct(FECHA_PUBLICACION_CONTRATO),
        RUC_DESTINATARIO_PAGO = as.character(RUC_DESTINATARIO_PAGO),
        MONEDA = as.character(MONEDA),
        MONTO_CONTRATADO_TOTAL = as.numeric(MONTO_CONTRATADO_TOTAL),
        MONTO_CONTRATADO_ITEM = as.numeric(MONTO_CONTRATADO_ITEM),
        DESCRIPCION_PROCESO = as.character(DESCRIPCION_PROCESO),
        CODIGOCONVOCATORIA = as.character(CODIGOCONVOCATORIA)
    )

df_2021 <- read_xlsx("data/01_raw/CONOSCE/CONOSCE_CONTRATOS2021_0.xlsx") 
df_2021 <- df_2021 %>%
    transmute(
        CODIGO_CONTRATO = CODIGO_CONTRATO,
        NUM_CONTRATO = NUM_CONTRATO,
        FECHA_VIGENCIA_INICIAL = FECHA_VIGENCIA_INICIAL,
        FECHA_VIGENCIA_FINAL = FECHA_VIGENCIA_FINAL,
        FECHA_SUSCRIPCION_CONTRATO = FECHA_SUSCRIPCION_CONTRATO,
        FECHA_PUBLICACION_CONTRATO = FECHA_PUBLICACION_CONTRATO,
        RUC_DESTINATARIO_PAGO = RUC_DESTINATARIO_PAGO,
        MONEDA = MONEDA,
        MONTO_CONTRATADO_TOTAL = MONTO_CONTRATADO_TOTAL,
        MONTO_CONTRATADO_ITEM = MONTO_CONTRATADO_ITEM,
        DESCRIPCION_PROCESO = DESCRIPCION_PROCESO,
        CODIGOCONVOCATORIA = CODIGOCONVOCATORIA,
        MODALIDAD = NA,
        TIPO_PROCESO = NA
    ) %>%
    mutate(
        CODIGO_CONTRATO = as.character(CODIGO_CONTRATO),
        NUM_CONTRATO = as.character(NUM_CONTRATO),
        FECHA_VIGENCIA_INICIAL = as.POSIXct(FECHA_VIGENCIA_INICIAL),
        FECHA_VIGENCIA_FINAL = as.POSIXct(FECHA_VIGENCIA_FINAL),
        FECHA_SUSCRIPCION_CONTRATO = as.POSIXct(FECHA_SUSCRIPCION_CONTRATO),
        FECHA_PUBLICACION_CONTRATO = as.POSIXct(FECHA_PUBLICACION_CONTRATO),
        RUC_DESTINATARIO_PAGO = as.character(RUC_DESTINATARIO_PAGO),
        MONEDA = as.character(MONEDA),
        MONTO_CONTRATADO_TOTAL = as.numeric(MONTO_CONTRATADO_TOTAL),
        MONTO_CONTRATADO_ITEM = as.numeric(MONTO_CONTRATADO_ITEM),
        DESCRIPCION_PROCESO = as.character(DESCRIPCION_PROCESO),
        CODIGOCONVOCATORIA = as.character(CODIGOCONVOCATORIA)
    )

# Combine datasets
combined_df_contratos <- bind_rows(df_2010_2017)#, df_2018, df_2019, df_2020, df_2021) %>%
    # select(CODIGO_CONTRATO, NUM_CONTRATO, FECHA_VIGENCIA_INICIAL,
    #        FECHA_VIGENCIA_FINAL, FECHA_SUSCRIPCION_CONTRATO,
    #        FECHA_PUBLICACION_CONTRATO, RUC_DESTINATARIO_PAGO,
    #        MONEDA, MONTO_CONTRATADO_TOTAL, MONTO_CONTRATADO_ITEM,
    #        DESCRIPCION_PROCESO, CODIGOCONVOCATORIA, MODALIDAD, TIPO_PROCESO)

skim_without_charts(combined_df_contratos)

# Write the combined dataset to a new CSV file
write.csv(combined_df_contratos, "data/02_intermediate/OSCE/combined_contratos_data.csv", row.names = FALSE)
write_parquet(combined_df_contratos, "data/02_intermediate/OSCE/combined_contratos_data.parquet")
